[build]
  functions = "netlify/functions"   # Dossier contenant vos fonctions Lambda
  publish = "/"

[dev]
  command = "npm run dev"            # Commande pour démarrer le serveur en local
  port = 8888 
